Feature/gh 933 restricted transactions
gnosis/safe-ios-legacy pull request #1041
Opened 2019-08-05 09:50 UTC by sche

closes #933

![IMG_2548](https://user-images.githubusercontent.com/2284385/62455659-2b7b4180-b777-11e9-9600-4f45ea6670b7.jpg)

2019-08-05 10:46 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
> +                    // guard tx is not dangerouse, otherwise show alert
typo: `dangerouse` -> `dangerous`

2019-08-05 10:46 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
> +                    // guard tx is not dangerouse, otherwise show alert
where is the guard?

2019-08-05 10:46 UTC, DmitryBespalov approved these changes

2019-08-06 08:42 UTC, DmitryBespalov requested changes
Overall is ok, but I had some questions.

2019-08-06 08:42 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletApplication/TransactionData.swift
> +                                              status: .rejected,
Where is this `empty` constant is used? Will the `status: .waitingForConfirmation` be a better option?

2019-08-06 08:42 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
> +        // We don't allow dangerous transactions initiated by browser extension.
I think the code is obvious here, the comment would be more useful if it would answer why we don't allow it, and not what is the code doing.

2019-08-06 08:42 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
> +        // TODO: TransactionStatus.Code.allCases
can this be used now after updating to Swift 5?

2019-08-06 08:42 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
> +            } catch { // dangerous transaction
Since we have the actual error available from the application service, I think it is better to catch it specifically:

```
} catch WalletApplicationServiceError.validationFailed {
...
}

the `validationFailed` may be not very specific for that case - maybe we need to create a separate error for the restricted transaction.

2019-08-06 08:42 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
> +        walletService.shouldThrow = true
If the specific error will be used, then this test will need to be adjusted

2019-08-06 08:42 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
> +        // TODO: use allCases
can we use it now? (I saw the Swift 5 change in this PR)

2019-08-06 08:49 UTC, sche commented on MultisigWallet/MultisigWalletApplication/TransactionData.swift
> +                                              status: .rejected,
```
private func doRequest() {
        doAfterEstimateTransaction { [weak self] in
            guard let `self` = self else { return TransactionData.empty }
            return try ApplicationServiceRegistry.walletService.requestTransactionConfirmationIfNeeded(self.tx.id)
        }
    }

    private func doSubmit() {
        doAfterEstimateTransaction { [weak self] in
            guard let `self` = self else { return TransactionData.empty }
            return try ApplicationServiceRegistry.walletService.submitTransaction(self.tx.id)
        }
    }
```
if self does not exist, I would treat it as rejected.

2019-08-06 08:53 UTC, sche commented on MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
> +        // We don't allow dangerous transactions initiated by browser extension.
will add more details in next pr.

2019-08-06 08:54 UTC, sche commented on MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
> +        // TODO: TransactionStatus.Code.allCases
I tried. It seems this feature will be available in Swift 5.1

2019-08-06 08:55 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
> +            } catch { // dangerous transaction
Ok, will change in next pr.

2019-08-06 08:57 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
> +        walletService.shouldThrow = true
ok

2019-08-06 08:57 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
> +        // TODO: use allCases
replied earlier

2019-08-06 09:00 UTC, DmitryBespalov approved these changes

2019-08-06 09:01 UTC, merged