Feature/gh 1060 contract intro
gnosis/safe-ios-legacy pull request #1105
Opened 2019-08-16 12:58 UTC by DmitryBespalov

closes #1060 
closes #1061 

It was easier to make everything in one sweep.

2019-08-16 13:00 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
> -        if ApplicationServiceRegistry.walletService.latestContractVersion == "1.0.0" {
@sche 

I removed it here because I thought with the next contract update there will be a different onboarding.. or even will stay the same but the link might change.. I think it's simpler to keep the onboarding as is right now.

2019-08-19 08:33 UTC, sche commented on MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainServiceTests.swift
> +        let metadata = SafeContractMetadata(multiSendContractAddress: .testAccount1,
code duplication with prev. test case

2019-08-19 08:43 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
> -        if ApplicationServiceRegistry.walletService.latestContractVersion == "1.0.0" {
The content of the first screen is only relevant for the upgrade to version 1.0.0. With the next upgrade, the 1st screen will be completely different, and we would need to return this code.
I would leave it without changes.

2019-08-19 08:45 UTC, sche requested changes
We need to discuss onboarding screens.

2019-08-19 09:00 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
> -        if ApplicationServiceRegistry.walletService.latestContractVersion == "1.0.0" {
okay, will do in other PR

2019-08-19 10:52 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainServiceTests.swift
> +        let metadata = SafeContractMetadata(multiSendContractAddress: .testAccount1,
ok, fixed in next pr

2019-08-19 10:56 UTC, sche approved these changes

2019-08-19 10:57 UTC, merged