Feature/GH-242 reveal password
gnosis/safe-ios-legacy pull request #1353
Opened 2019-12-05 16:34 UTC by MoaazThahabee

Create and use reveal password feature

2019-12-05 16:46 UTC, sche commented on SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
> +        guard let togglePasswordButton = self.togglePasswordButton else {return}
Please use spaces
```
{ return }
```

2019-12-05 16:51 UTC, sche commented
👍

2019-12-06 09:48 UTC, DmitryBespalov requested changes
Good job! A few more steps and we're done here.

2019-12-06 09:48 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
> +                self.rigthView = button
To be consistent with the project's style, the variables outside of closures should omit `self`.

2019-12-06 09:48 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
> +        self.isSecure = !self.isSecure
here, too, `self`s are not needed

2019-12-06 10:13 UTC, DmitryBespalov approved these changes

2019-12-06 10:45 UTC, merged