Feature/gh 1370 walletconnect scanner screen adjustments
gnosis/safe-ios-legacy pull request #1372
Opened 2019-12-12 15:57 UTC by MouazAlzahabi

GH-1370 WalletConnect Scanner Screen Adjustments

2019-12-13 10:57 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
> +        scanButtonItem.scanHeader = LocalizedString("scan_wallet_connect", comment: "Scan WalletConnect QR code")
please place LocalizedString in enum Strings

2019-12-13 10:58 UTC, DmitryBespalov requested changes
Good 👍. Almost done - some small polishing left for it to be ready.

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
> +    var header: String?
please add a blank line between variable and enum declaration (after this line)

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
> +    var header: String?
please add a blank line after this line

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
> +
please remove trailing whitespace

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
> -
please add the blank line back for consistency

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.xib
> +                <constraint firstItem="AdF-AR-sr9" firstAttribute="width" secondItem="i5M-Pr-FkT" secondAttribute="width" id="1Wj-Gy-xne"/>
The frame will look nicer if we add a 3pt inset of the overlay inside the frame.

Please make the constraints of the dimming views to overlap the "frame" image with 3pt

2019-12-13 10:58 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
Small improvement: let's make the status bar white, so it is visible on the dark dimmed background.

```
    override var preferredStatusBarStyle: UIStatusBarStyle {
        .lightContent
    }
```

2019-12-13 10:59 UTC, sche commented on SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInput.swift
> +    public var scanHeader: String? {
I am not sure if we use this component at all. Probably we just should delete it.

2019-12-13 11:01 UTC, sche commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
> +
does linter show warning on this line now?

2019-12-17 10:29 UTC, MouazAlzahabi commented on SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInput.swift
> +    public var scanHeader: String? {
True, It's not used so far but I added it for consistency as I did for all components that use QRScanner.

2019-12-17 13:33 UTC, DmitryBespalov approved these changes

2019-12-17 13:53 UTC, MouazAlzahabi commented
closes #1370

2019-12-17 13:56 UTC, merged