Feature/gh 1336 universal scan button
gnosis/safe-ios-legacy pull request #1386
Opened 2019-12-16 17:05 UTC by MouazAlzahabi

GH 1336 universal scan button

2019-12-16 17:23 UTC, DmitryBespalov requested changes
Good that the code is mostly with the style as the other code. Also, a good base for the future adding address scanning to the universal flow. 

I found that some minor code style changes needed.

2019-12-16 17:23 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +    public static let shared = UniversalScanFlowCoordinator()
[code style]: please add a blank line before this line

2019-12-16 17:23 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +            return code
I think it's ok to replace these 2 lines with just `code.starts(with: "wc:") ? code :  nil`

2019-12-16 17:23 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +            guard let self = self else { return }
don't we need to use `` `self` `` instead of plain "self"?

2019-12-16 17:23 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
> +    public init() {
let's just make it one line: `public init() {}`

2019-12-17 13:34 UTC, DmitryBespalov submitted a review, later dismissed

2019-12-17 15:44 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
> +    }
please add an empty line here

2019-12-17 16:25 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +    static func create(next: @escaping () -> Void, finish: @escaping () -> Void) -> OnboardingViewController {
please add spacing here

2019-12-17 16:27 UTC, sche commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +    static func create(next: @escaping () -> Void, finish: @escaping () -> Void) -> OnboardingViewController {
this introduces code duplication with WalletConnectFlowCoordinator. Can you reuse the implementation?

2019-12-18 11:00 UTC, DmitryBespalov approved these changes
👍

2019-12-18 11:00 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/MainFlow/Universal/UniversalScanFlowCoordinator.swift
> +            `self`.sessionListController = vc
when we declared `` `self` `` in the `guard`, then we can use it as `self`, without apostrophes.

2019-12-18 12:27 UTC, sche commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
> +    public init() { }
no space needed inside {}

2019-12-18 12:28 UTC, sche commented on SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
> +    }
please add extra-space

2019-12-18 12:29 UTC, sche approved these changes
It looks good to me. Some minor style adjustments left.

2019-12-19 08:59 UTC, DmitryBespalov commented
I will merge this, please make another PR for tests

2019-12-19 08:59 UTC, merged