Feature/ghi 358 tx list design
gnosis/safe-ios-legacy pull request #403
Opened 2018-11-24 12:20 UTC by DmitryBespalov

closes #358

2018-11-24 12:27 UTC, sche commented on Common/Common.xcodeproj/project.pbxproj
> +		0AD1D1E421A8482800941EA1 /* Dasta+Padding.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0AD1D1E321A8482800941EA1 /* Dasta+Padding.swift */; };
What is Dasta?

2018-11-24 12:28 UTC, DmitryBespalov commented on Common/Common.xcodeproj/project.pbxproj
> +		0AD1D1E421A8482800941EA1 /* Dasta+Padding.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0AD1D1E321A8482800941EA1 /* Dasta+Padding.swift */; };
🤣

2018-11-24 12:49 UTC, sche commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionTableViewCell.swift
> +public class EthereumAddressLabel: BaseCustomLabel {
Could you put it into components with demo vc?

2018-11-24 12:53 UTC, sche commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionsTableViewController.swift
> +        tableView.register(ShadowFooterView.self, forHeaderFooterViewReuseIdentifier: "ShadowFooterView")
There is an issue with ShadowFooterView that when there are a lot of cells on a screen, it is always visible. Try to add many tokens for Assets.

2018-11-24 12:54 UTC, sche commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionsGroupHeaderView.swift
>  class TransactionsGroupHeaderView: UITableViewHeaderFooterView {
Would be nice to unify with Header view for Menu

2018-11-24 13:04 UTC, sche commented on SafeUIKit/SafeUIKit/EthereumAddressFormatter.swift
> +    case mixedcased
how about "checksummed" ?

2018-11-24 13:08 UTC, sche commented on SafeUIKit/SafeUIKit/EthereumAddressFormatterTests.swift
> +        XCTAssertEqual(formatter.string(from: "0x1"), "0x0000000000000000000000000000000000000001")
What would be the use case for that?

2018-11-24 13:10 UTC, sche requested changes
Well done! A lot of work.

2018-11-26 10:01 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionTableViewCell.swift
> +public class EthereumAddressLabel: BaseCustomLabel {
I'd like to do that in a separate PR

2018-11-26 10:01 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionsGroupHeaderView.swift
>  class TransactionsGroupHeaderView: UITableViewHeaderFooterView {
I'd like to do that in a separate PR

2018-11-26 10:42 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/AppFlow/MainFlow/Transactions/TransactionsTableViewController.swift
> +        tableView.register(ShadowFooterView.self, forHeaderFooterViewReuseIdentifier: "ShadowFooterView")
yes, I'll remove it according to new design requirements

2018-11-26 10:42 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/EthereumAddressFormatter.swift
> +    case mixedcased
I'd keep mixed case, because it is consistent with other names, and 'checksummed' doesn't tell anything

2018-11-26 10:43 UTC, DmitryBespalov commented on SafeUIKit/SafeUIKit/EthereumAddressFormatterTests.swift
> +        XCTAssertEqual(formatter.string(from: "0x1"), "0x0000000000000000000000000000000000000001")
here I'm violating `You Ain't Gonna Need It` principle, but I'd keep it, it's just nice.

2018-11-26 10:44 UTC, sche approved these changes

2018-11-26 11:03 UTC, merged