Feature/ghi 406 requesting signatures
gnosis/safe-ios-legacy pull request #407
Opened 2018-11-27 16:50 UTC by sche

requesting signatures logic

2018-11-28 09:08 UTC, DmitryBespalov requested changes

2018-11-28 09:08 UTC, DmitryBespalov commented on Common/Common/OneOperationWaitinScheduler.swift
> +/// It allows to have only one opetion in a queue to execute.
typo: `opetion` -> `operation`

2018-11-28 09:08 UTC, DmitryBespalov commented on Common/Common/OneOperationWaitinScheduler.swift
> +public final class OneOperationWaitinScheduler {
typo: `Waitin` -> `Waiting`?

2018-11-28 09:08 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
> +            // TODO: unit test this
please unit test this

2018-11-28 09:08 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
> +            showTransactionNeedsConfirmationAlert()
can't we disable the 'submit' button until the tx is ready to submit?

2018-11-28 09:08 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
> +            showTransactionNeedsConfirmationAlert()
or is it a desing requirement for this behavior?

2018-11-28 09:08 UTC, DmitryBespalov commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewControllerTests.swift
> +    // TODO: test_whenSubmittingConfirmedTransactonAndAllowed_thenCallesDelegateOnSuccess
is this going to be implemented in the next PR?

2018-11-28 09:08 UTC, DmitryBespalov commented on TestTools/XCTest+Alert.swift
> +                                actionsCount: Int = 1,
please rename `actionsCount` to `actionCount`

2018-11-28 13:51 UTC, sche commented on Common/Common/OneOperationWaitinScheduler.swift
> +/// It allows to have only one opetion in a queue to execute.
done

2018-11-28 13:52 UTC, sche commented on Common/Common/OneOperationWaitinScheduler.swift
> +public final class OneOperationWaitinScheduler {
done

2018-11-28 13:53 UTC, sche commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
> +            showTransactionNeedsConfirmationAlert()
Now we designed it like that. Let's see what will change today...

2018-11-28 13:53 UTC, sche commented on SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewControllerTests.swift
> +    // TODO: test_whenSubmittingConfirmedTransactonAndAllowed_thenCallesDelegateOnSuccess
I will implement in this PR

2018-11-28 13:54 UTC, sche commented on TestTools/XCTest+Alert.swift
> +                                actionsCount: Int = 1,
done

2018-11-29 09:40 UTC, DmitryBespalov approved these changes

2018-11-29 09:48 UTC, merged