Refactors Token.swift improving readability
gnosis/safe-ios-legacy pull request #568
Opened 2019-02-24 10:51 UTC by valeriyvan

2019-02-25 15:58 UTC, DmitryBespalov requested changes

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> -    public init(code: String, name: String, decimals: Int, address: Address, logoUrl: String) {
when this is removed, the compiler generates `internal init` instead of `public`, and this makes this class cannot be instantiated from other modules. Please add it back, or if there's a method to tweak compiler settings...

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> -    public init(amount: TokenInt, token: Token) {
same here, the public init is not generated, that's why we do it by hand

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +// MARK: - TokenAmount failable initializer from a String
I'd put `TokenAmount from String` instead this comment, as it is clear that the init is failable from the code itself.

Also, I'm not sure if two extensions with 1 method each is a good thing here, why was it split?

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +    fileprivate static let separator = "==="
please put the variables to the top of the extension definition (coding style)

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +    fileprivate static let separator = "~~~"
please move this line before the init (coding style: put vars/constants to the top of the type/extension declarations)

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +        guard let amount = TokenInt(components[0]), let token = Token(components[1]) else {
the code would improve even more, if we would merge two guards. What do you think?

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +        return [String(amount), token.description].joined(separator: TokenAmount.separator)
👍

2019-02-26 14:18 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> -    public init(code: String, name: String, decimals: Int, address: Address, logoUrl: String) {
reverted init removal

2019-02-26 14:18 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +// MARK: - TokenAmount failable initializer from a String
Fixed comment

2019-02-26 14:23 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +// MARK: - TokenAmount failable initializer from a String
If protocol conformances go into separate extension(s) it makes sense to have in extension only stuff related to protocol. Otherwise it brings question if stuff here because it is somehow related to protocol. CustomStringConvertible declares only description property. That why I move failable initializer into its own extension.

2019-02-26 14:24 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> -    public init(amount: TokenInt, token: Token) {
reverted memberwise init removal

2019-02-26 14:27 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +    fileprivate static let separator = "==="
Moved on top. 

The reason it was on bottom because this static member is private implementation detail, and all implementation detaisl go bottom not to distract from what's is more important.

2019-02-26 14:27 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +    fileprivate static let separator = "~~~"
moved top

2019-02-26 14:27 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +        return [String(amount), token.description].joined(separator: TokenAmount.separator)
combined guards

2019-02-26 14:28 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/Token.swift
> +        guard let amount = TokenInt(components[0]), let token = Token(components[1]) else {
combined guards

2019-02-26 14:28 UTC, valeriyvan commented
Fixed all issues

2019-02-28 09:10 UTC, DmitryBespalov approved these changes

2019-02-28 09:10 UTC, merged