Makes ExtensionCode Decodable what it by nature is
gnosis/safe-ios-legacy pull request #583
Opened 2019-02-25 13:29 UTC by valeriyvan

Get rid of JSONSerialization usage.

2019-02-25 15:58 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +    // This is inside to avoid clashing with Signature aka Transaction owner signature.
imo this is fine, comment not needed here

2019-02-25 16:02 UTC, DmitryBespalov requested changes

2019-02-25 16:02 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +        let vInt: Int
These names were used in previous init to distinguish the vars from actual values. In this case, after the struct is extracted, we could use `v`, `r`, `s` directly.

2019-02-25 16:02 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +        let sStr = signature.sStr
imo, these variables could be inlined

2019-02-25 16:02 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +    struct Signature: Decodable {
if you'd like, this Signature could be renamed to JSONSignature or something like it so that it's clear that it is used only for deserialization

2019-02-25 16:02 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +extension ExtensionCode: Decodable {
I like it

2019-02-26 13:15 UTC, valeriyvan commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +    // This is inside to avoid clashing with Signature aka Transaction owner signature.
renamed it, moved out and made private

2019-02-26 13:15 UTC, valeriyvan commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +        let vInt: Int
got rid of

2019-02-26 13:15 UTC, valeriyvan commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +    struct Signature: Decodable {
renamed

2019-02-26 13:15 UTC, valeriyvan commented on MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
> +extension ExtensionCode: Decodable {
👍🏿

2019-02-28 09:10 UTC, DmitryBespalov approved these changes

2019-02-28 09:10 UTC, merged