Retry with increasing delay
gnosis/safe-ios-legacy pull request #588
Opened 2019-02-26 15:31 UTC by valeriyvan

2019-02-28 09:07 UTC, DmitryBespalov approved these changes

2019-02-28 09:09 UTC, DmitryBespalov commented
this breaks some unit tests, I need to take a closer look a bit late

2019-02-28 09:11 UTC, valeriyvan commented
On my side tests pass.

2019-02-28 09:13 UTC, DmitryBespalov commented
ok, I restarted the build

2019-02-28 09:29 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Wallet/RetryWithIncreasingDelay.swift
> +                Common.Timer.wait(TimeInterval(attempt) * delay)
in the old code, the `attempt` is used to calculate the delay. At the time of calling the wait, it would be non-zero. In this code, the `attempt` may be `0` the first time, so the code needs to be:

```
Common.Timer.wait(TimeInterval(attempt + 1) * delay)
```

2019-02-28 09:29 UTC, DmitryBespalov requested changes

2019-02-28 09:29 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Wallet/RetryWithIncreasingDelay.swift
> +                Common.Timer.wait(TimeInterval(attempt) * delay)
or change the range of the for loop to 1-based: `1...maxAttempts`

2019-02-28 09:31 UTC, DmitryBespalov commented on MultisigWallet/MultisigWalletDomainModel/Wallet/RetryWithIncreasingDelay.swift
> +                Common.Timer.wait(TimeInterval(attempt) * delay)
in the ^^^ case, we need to then pass `attempt - 1` to `main` call

2019-03-01 09:30 UTC, valeriyvan commented on MultisigWallet/MultisigWalletDomainModel/Wallet/RetryWithIncreasingDelay.swift
> +                Common.Timer.wait(TimeInterval(attempt) * delay)
changed

2019-03-11 10:11 UTC, DmitryBespalov approved these changes

2019-03-27 09:57 UTC, merged